apiVersion: v2
name: rocketchat
description: A Helm to deploy rocketchat with public DNS + TLS
type: application
version: 0.1.0
appVersion: "5.4.3"

dependencies:
  - name: rocketchat
    version: "5.4.3"
    repository: "https://rocketchat.github.io/helm-charts"
    condition: app.enabled
  - name: ingress-nginx
    version: "4.2.5"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: infra.enabled
  - name: external-dns
    version: "0.1.0"
    condition: infra.enabled
