apiVersion: v2
name: rocketchat
description: A Helm to deploy rocketchat with public DNS + TLS
type: application
version: 0.1.0
appVersion: "5.1.0"

dependencies:
  - name: rocketchat
    version: "5.1.0"
    repository: "https://rocketchat.github.io/helm-charts"
    condition: app.enabled
  - name: cert-manager
    version: "1.9.1"
    repository: "https://charts.jetstack.io"
    condition: infra.enabled
  - name: ingress-nginx
    version: "4.2.5"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: infra.enabled
  - name: azuredisk-csi-driver
    version: "1.0.1"
    repository: "https://raw.githubusercontent.com/edgelesssys/constellation-azuredisk-csi-driver/main/charts/edgeless"
    condition: infra.enabled
  - name: encrypted-az-disk
    version: "0.1.0"
    condition: infra.enabled
  - name: external-dns
    version: "0.1.0"
    condition: infra.enabled
