# Only deploy the respective ingress object if it does not already exist. Otherwise nginx complains about the host/path already being defined during upgrade.
{{- if .Values.app.enabled }}
{{- $exists := lookup "v1" "Ingress" .Release.Namespace "rocket-ingress" -}}
{{ if $exists }}
{{ else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocket-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: tls-cert
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-rocketchat
            port:
              number: 80
  ingressClassName: nginx
{{- end -}}
{{- end }}
